services:
  - type: web
    name: fintrack
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: fintrack
          property: connectionString
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://FinTrack.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: fintrack
    plan: free